# Generated by Django 3.1 on 2021-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210505_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
