# Generated by Django 3.1 on 2021-05-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
