# Generated by Django 3.1 on 2021-04-05 06:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('old_price', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('background', models.ImageField(blank=True, upload_to='background/')),
                ('registration_number', models.IntegerField(default=0)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (23, 23), (22, 22), (21, 21), (25, 25), (24, 24), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (32, 32), (31, 31), (33, 33)], default=33), blank=True, null=True, size=None)),
                ('description', models.CharField(default='', max_length=500)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, null=True)),
                ('reason', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'tbl_course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KeyActiveModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('key_active', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_active_course', to='course.coursemodel')),
            ],
            options={
                'db_table': 'tbl_key_active',
            },
        ),
        migrations.CreateModel(
            name='FeelingStudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_student_course', to='course.coursemodel')),
            ],
            options={
                'db_table': 'tbl_feeling_student',
            },
        ),
    ]
