# Generated by Django 3.1 on 2021-04-07 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210407_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_path/')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'tbl_video',
                'ordering': ['id'],
            },
        ),
    ]
