# Generated by Django 3.1 on 2021-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_videosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='upload_path'),
        ),
    ]
