# Generated by Django 3.1 on 2021-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210407_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='list_video',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
