# Generated by Django 3.1 on 2021-04-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursemodel_list_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='list_video',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
