# Generated by Django 3.1 on 2021-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210411_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, null=True),
        ),
    ]
