# Generated by Django 3.1 on 2021-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210504_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
