# Generated by Django 3.1 on 2021-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursemodel_course_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
